spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yz-nanfan-land?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    password: root123456

#参照配置文件generator.properties
